name = "CollisionDistance"
uuid = "326368f3-1fb6-41b4-8a0f-b3861d9497a8"
authors = ["malenickymartin"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
